name: notes_app
description: "Notes, una app de notas rapida y moderna."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.3
  path: ^1.9.0
  uuid: ^4.4.0
  local_auth: ^2.2.0
  flutter_secure_storage: ^9.2.2
  cupertino_icons: ^1.0.8
  flutter_slidable: ^3.1.1
  flex_color_scheme: ^7.3.1
  intl: ^0.19.0
  collection: ^1.18.0
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  drift_dev: ^2.16.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
